### PR TITLE
Word count continues to increase after goal met

### LINKED ISSUE #222: Word count continues to count up after reaching goal.
Currently, the word count stops counting up once you have reached your goal. I.E. if your goal is 500 words it will reach 500/500 words, and count no further. With this set-up there is no way to tell how many words you have written in a session once you have reached your goal. My request is for your session word count to continue to rise once you have reached your goal. I.E. 775/500.

Alternatively, the ability to see the word count of a highlighted selection would be nice, such as ctrl+shift+C in google docs.

### PR DESCRIPTION
**Pull request by MadCatMagic**
Fixes #222, along with a setting to disable the new behaviour.

### CODE REVIEW

**Comment by MadCatMagic** [comment]
I am not sure whether this actually requires a setting, since you don't lose anything by enabling it. You can still see your goal next to it.

**Comment by kevboh** [comment]
Thanks, this is great! I don't think this needs a setting—I can't see why people wouldn't want the new behavior as a default. Can you remove the setting, after which I can merge.

**Comment by MadCatMagic** [comment]
Done!

**Comment by kevboh** [comment]
Thanks! I ended up rebasing and fixing some formatting as https://github.com/kevboh/longform/tree/word-count-after-goal. Will merge that and close this. Thank you!

**Pull request closed without merging**
