### PR TITLE
fix: use 'Scenes' tab as default (#141)

### LINKED ISSUE #141: Feature Request: Use Scene View as Default tab, not Drafts View
**Describe the solution you'd like**
More a quality-of-life feature, but I find it quite annoying that every time I open up the Longform Sidebar, it opens the Drafts Tab. Considering that since Longform 2.0 Drafts are a less important feature, and you can easily make due without using Drafts, it's a bit annoying the plugin still constantly opens the Drafts Tab by default.

**Describe alternatives you've considered**
I cannot think of one.

### PR DESCRIPTION
**Pull request by chrisgrieser**
fixes #141

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Hmm, upon some usage, it appears that this fix has the weird drawback of somewhat breaking the tabs. Once the compile tab is selected, the longform sidebar is broken, whichever tab you then choose. 

Tried scouring the code base and could not really find out why, and also could not find out any other locatin where the default tab might be set, so I am a bit puzzled here.

**Comment by b-camphart** [comment]
@chrisgrieser when you see that issue, is "A Short Story" or "An Essay" the project that's currently selected?  I think the issue arises due to single-scene projects not having scene compile steps (errors are thrown before you even click the Compile tab).

**Comment by b-camphart** [comment]
Somehow, steps are being added to the workflow that are `undefined` which throws an error when deserializing, but also throws an error when the Compile tab is clicked.  When an error is thrown from the GUI, the svelte engine stops working, which is why it becomes unresponsive.

**Comment by chrisgrieser** [comment]
Yeah, That's habe exactly zero prior experience with svelte, so...

Anyway, what would be the solution for this? Maybe simmering like selecting the project tab first and then selecting the scenes tab maybe?

**Comment by b-camphart** [comment]
I didn't do a full deep-dive to figure out where the `undefined` steps were coming from, but I think it has to do with how the settings are saved and/or loaded.  We don't have `strictNullChecks` enabled in the tsconfig.json, so it's hard to tell where the problem might originate.  If you don't want to debug this whole thing, maybe the place to make this feature work is in the GUI, instead of the store, since the "Scenes" tab doesn't necessarily apply to all projects.

**Comment by chrisgrieser** [comment]
hmm, yeah, I guess I simply lack the knowledge of svelte to figure out where to do this GUI-wise. Guess we'll have to wait for pointers from kevboh

**Comment by chrisgrieser** [comment]
Happens as soon as I switch to the compile tab. I have my one multi-scene project selected the whole time (don't have any single scene projects to begin with)

**Comment by kevboh** [comment]
Closing in favor of https://github.com/kevboh/longform/pull/206

**Pull request closed without merging**
